### ISSUE TITLE
Django 1.7 - exception when using AppConfig

### ISSUE THREAD

**Issue by bmihelac** [mbi/django-rosetta#113]
Currently rosetta loops through applications in `INSTALLED_APPS` and try to get `locale` directory for each app. Django 1.7. [applications refactor](https://docs.djangoproject.com/en/dev/ref/applications/) allows to add `AppConfig` class instead of module. This makes rosetta raise exception:

```
  File ".../rosetta/poutil.py", line 83, in find_pos
    apppath = os.path.normpath(os.path.abspath(os.path.join(os.path.dirname(app.__file__), 'locale')))
AttributeError: type object 'MYAPPCONFIG' has no attribute '__file__'
```

Workaround for this is to add this AppConfig to `ROSETTA_EXCLUDED_APPLICATIONS`.

**Comment by mbi** [comment]
Thanks for reporting this issue. I haven't yet started looking into Django 1.7's `AppConfig` classes. Could I kindly ask you to provide a sample app with an AppConfig that triggers this bug? 

Cheers.

**Comment by bmihelac** [comment]
Here it is: https://github.com/bmihelac/django-rosetta/tree/113-testapp

**Comment by mbi** [comment]
Thanks. Sorry, I must be dense, but with your change all my tests fail with an entirely different error, i.e. 

`LookupError: No installed app with label 'django.contrib.redirects'.`

Also, the redirect app [documentation](https://docs.djangoproject.com/en/1.7/ref/contrib/redirects/) suggests to simply add `django.contrib.redirects` to `INSTALLED_APPS` not the entire path to the AppConfig class.

What am I missing here?

**Comment by bmihelac** [comment]
When adding 'django.contrib.redirects' to `INSTALLED_APPS` dajngo will look for `default_app_config`(this is https://github.com/django/django/blob/master/django/contrib/redirects/__init__.py) and use this to configure app.

In test code I used  full name of AppConfig class for redirects app which is valid. If you try to start testproject, Redirects app will be in admin and behave as it should, but rosetta.

I would say that we need to use  [AppConfig.module](https://docs.djangoproject.com/en/dev/ref/applications/#django.apps.AppConfig.module) instead of `app.__file__` in poutil.py.

**Comment by mbi** [comment]
Just to make sure, are you testing against the latest HEAD or the last point release?

**Comment by bmihelac** [comment]
Dajngo 1.7, rosetta HEAD

**Comment by kuyucakli** [comment]
Hello,

Is there any progress on this issue? I am getting AttributeError at /rosetta/
'module' object has no attribute '**file**'   via my 1.7 django application...

Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/rosetta/

Django Version: 1.7.1
Python Version: 3.3.2
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'ckeditor',
 'modeltranslation',
 'apps.web',
 'libs.custom_auth',
 'rosetta')
Installed Middleware:
('django.middleware.gzip.GZipMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')

Traceback:
File "/Users/burakk/BurakWorks/Web/VIRTUAL_ENVIRONMENTS/django_python3.3/lib/python3.3/site-packages/django/core/handlers/base.py" in get_response
1.                     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
   File "/Users/burakk/BurakWorks/Web/VIRTUAL_ENVIRONMENTS/django_python3.3/lib/python3.3/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
2.         response = view_func(request, _args, *_kwargs)
   File "/Users/burakk/BurakWorks/Web/VIRTUAL_ENVIRONMENTS/django_python3.3/lib/python3.3/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
3.                 return view_func(request, _args, *_kwargs)
   File "/Users/burakk/BurakWorks/Web/VIRTUAL_ENVIRONMENTS/django_python3.3/lib/python3.3/site-packages/rosetta/views.py" in home
4.         return list_languages(request, do_session_warn=True)
   File "/Users/burakk/BurakWorks/Web/VIRTUAL_ENVIRONMENTS/django_python3.3/lib/python3.3/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
5.         response = view_func(request, _args, *_kwargs)
   File "/Users/burakk/BurakWorks/Web/VIRTUAL_ENVIRONMENTS/django_python3.3/lib/python3.3/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
6.                 return view_func(request, _args, *_kwargs)
   File "/Users/burakk/BurakWorks/Web/VIRTUAL_ENVIRONMENTS/django_python3.3/lib/python3.3/site-packages/rosetta/views.py" in list_languages
7.         pos = find_pos(language[0], project_apps=project_apps, django_apps=django_apps, third_party_apps=third_party_apps)
   File "/Users/burakk/BurakWorks/Web/VIRTUAL_ENVIRONMENTS/django_python3.3/lib/python3.3/site-packages/rosetta/poutil.py" in find_pos
8.     abs_project_path = os.path.normpath(os.path.abspath(os.path.dirname(project.**file**)))

Exception Type: AttributeError at /rosetta/
Exception Value: 'module' object has no attribute '**file**'

**Comment by kuyucakli** [comment]
ok i have put **init**.py to my application folder and the problem is gone.

**Comment by kuyucakli** [comment]
Hi, i was testing my application locally and i thought i solved the problem but on the far server i can not make rosetta work. ( even by putting init.py to my app ) .

**Comment by mbi** [comment]
Ok, this _might_ be fixed in 6d474d74d48d550f907141ae6534680ed3047350
I'd be grateful if you could check out HEAD and give a test.

**Comment by kuyucakli** [comment]
Hi,

I want to try this fix how can i upgrade rosetta to 6d474d7  using pip?

**Comment by mbi** [comment]
@burakk to get the latest HEAD:

`pip uninstall django-rosetta`

then:

`pip install git+https://github.com/mbi/django-rosetta.git#egg=django-rosetta-dev`

Thank you.

**Comment by kuyucakli** [comment]
Sorry... I am still getting

 [Mon Mar 02 21:12:22 2015] [error]   File "/home/mehmet/lib/python3.4/rosetta/poutil.py", line 58, in find_pos
[Mon Mar 02 21:12:22 2015] [error]     abs_project_path = os.path.normpath(os.path.abspath(os.path.dirname(project.**file**)))
[Mon Mar 02 21:12:22 2015] [error] AttributeError: 'module' object has no attribute '**file**'
[Mon Mar 02 21:12:22 2015] [error] 

Do i need to add project_path? Locally everything works fine.  Can i fix this temporarily? Because i have to give the rosetta link to one of my customers...

**Comment by burakk** [comment]
Do i need to add project_path? Locally everything works fine.

**Comment by burakk** [comment]
Can i fix this temporarily? Because i have to give the rosetta link to one of my customers...

**Comment by mbi** [comment]
Hmm, what is your `settings.SETTINGS_MODULE` ?

**Comment by kuyucakli** [comment]
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "lifetlarose_convent.settings.prod")

my settings are in a settings folder under lifetlarose_convent application and prod.py imports some setting parameters from common.py  I am using a dev setting file for local and a prod setting file for far server... I am changing them in wsgi.py and manage.py

**Comment by mbi** [comment]
A workaround would probably to create a `__init__.py` file inside lifetlarose_convent, am I correct in assuming it doesn't have one at the moment?

**Comment by burakk** [comment]
I have added one with no change in result.  I am still getting server error 500 with a  traceback as -->

[Mon Mar 02 21:12:22 2015] [error] Internal Server Error: /rosetta/
[Mon Mar 02 21:12:22 2015] [error] Traceback (most recent call last):
[Mon Mar 02 21:12:22 2015] [error]   File "/home/mehmet/webapps/lifetlarose_convent/lib/python3.4/Django-1.7.1-py3.4.egg/django/core/handlers/base.py", line 111, in get_response
[Mon Mar 02 21:12:22 2015] [error]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Mon Mar 02 21:12:22 2015] [error]   File "/home/mehmet/webapps/lifetlarose_convent/lib/python3.4/Django-1.7.1-py3.4.egg/django/views/decorators/cache.py", line 52, in _wrapped_view_func
[Mon Mar 02 21:12:22 2015] [error]     response = view_func(request, *args, **kwargs)
[Mon Mar 02 21:12:22 2015] [error]   File "/home/mehmet/webapps/lifetlarose_convent/lib/python3.4/Django-1.7.1-py3.4.egg/django/contrib/auth/decorators.py", line 22, in _wrapped_view
[Mon Mar 02 21:12:22 2015] [error]     return view_func(request, *args, **kwargs)
[Mon Mar 02 21:12:22 2015] [error]   File "/home/mehmet/lib/python3.4/rosetta/views.py", line 282, in home
[Mon Mar 02 21:12:22 2015] [error]     return list_languages(request, do_session_warn=True)
[Mon Mar 02 21:12:22 2015] [error]   File "/home/mehmet/webapps/lifetlarose_convent/lib/python3.4/Django-1.7.1-py3.4.egg/django/views/decorators/cache.py", line 52, in _wrapped_view_func
[Mon Mar 02 21:12:22 2015] [error]     response = view_func(request, *args, **kwargs)
[Mon Mar 02 21:12:22 2015] [error]   File "/home/mehmet/webapps/lifetlarose_convent/lib/python3.4/Django-1.7.1-py3.4.egg/django/contrib/auth/decorators.py", line 22, in _wrapped_view
[Mon Mar 02 21:12:22 2015] [error]     return view_func(request, *args, **kwargs)
[Mon Mar 02 21:12:22 2015] [error]   File "/home/mehmet/lib/python3.4/rosetta/views.py", line 349, in list_languages
[Mon Mar 02 21:12:22 2015] [error]     pos = find_pos(language[0], project_apps=project_apps, django_apps=django_apps, third_party_apps=third_party_apps)
[Mon Mar 02 21:12:22 2015] [error]   File "/home/mehmet/lib/python3.4/rosetta/poutil.py", line 58, in find_pos
[Mon Mar 02 21:12:22 2015] [error]     abs_project_path = os.path.normpath(os.path.abspath(os.path.dirname(project.__file__)))
[Mon Mar 02 21:12:22 2015] [error] AttributeError: 'module' object has no attribute '__file__'
[Mon Mar 02 21:12:22 2015] [error]

**Comment by kuyucakli** [comment]
Ok **init**.py solved the problem.
