### ISSUE TITLE
support for 1.4

### ISSUE THREAD

**Issue by lawgon** [mbi/django-rosetta#30]
on running rosetta in development trunk, I get this error

Environment:

Request Method: GET
Request URL: http://127.0.0.1:9999/rosetta/

Django Version: 1.4a1
Python Version: 2.7.2
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.admin',
 'django.contrib.staticfiles',
 'sorl.thumbnail',
 'south',
 'web',
 'modeltranslation',
 'rosetta')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.middleware.doc.XViewMiddleware')

Traceback:
File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
1.                         response = callback(request, _callback_args, *_callback_kwargs)
   File "/usr/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
2.                 return view_func(request, _args, *_kwargs)
   File "/usr/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
3.         response = view_func(request, _args, *_kwargs)
   File "/usr/lib/python2.7/site-packages/rosetta/views.py" in home
4.         return list_languages(request)
   File "/usr/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
5.                 return view_func(request, _args, *_kwargs)
   File "/usr/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
6.         response = view_func(request, _args, *_kwargs)
   File "/usr/lib/python2.7/site-packages/rosetta/views.py" in list_languages
7.     ADMIN_MEDIA_PREFIX = settings.ADMIN_MEDIA_PREFIX
   File "/usr/lib/python2.7/site-packages/django/utils/functional.py" in inner
8.         return func(self._wrapped, *args)

Exception Type: AttributeError at /rosetta/
Exception Value: 'Settings' object has no attribute 'ADMIN_MEDIA_PREFIX'

**Comment by mbi** [comment]
Fixed, thank you.

**Comment by lawgon** [comment]
would this fix be available through pip, or should I clone the dev code?

**Comment by mbi** [comment]
It wont be available until I release a new version trough PyPi, and that won't happen before 1.4 final lands, I'm afraid, so you're better off just cloning the repo or you could still install via pip:

```
pip install -e git+git://github.com/mbi/django-rosetta.git#egg=django-rosetta-dev
```

**Comment by lawgon** [comment]
actually the problem was not fixed. Earlier versions of django had a setting called ADMIN_MEDIA_PREFIX. That has been dropped in favour of STATIC_ROOT. I solved the problem by adding ADMIN_MEDIA_PREFIX = '/static/admin/' to settings.py

**Comment by curaloucura** [comment]
and this seems to still be an issue. just cloned using django 1.5.3 and i had no admin css files until I have added that settings. but it doesn't say anything on the readme file.
